name: Windows

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: configure
      run: |
        cmake -B build/debug   -G Ninja -D ZTD_IDK_TESTS=ON -D ZTD_IDK_EXAMPLES=ON -D ZTD_IDK_GENERATE_SINGLE=ON
        cmake -B build/release -G Ninja -D ZTD_IDK_TESTS=ON -D ZTD_IDK_EXAMPLES=ON -D ZTD_IDK_GENERATE_SINGLE=ON

    - name: build
      run: |
        cmake --build build/debug   --config Debug
        cmake --build build/release --config Release

    - name: test
      run: |
        cd build/debug
        ctest --build-config Debug
        cd ../..
        cd build/release
        ctest --build-config Release
        cd ../..
